src/clients/urls.py
from django.conf.urls import url

# from . import views

from .views import (
    client_list,
    client_create,
    client_detail,
    client_update,
    client_delete,
    download_report,
    vote_for_client,
    vote_for_client_poll,
    client_poll,
    )

urlpatterns = [
    url(r'^$', client_list, name="list"),
    url(r'^report/$', download_report, name="download_report"),
    url(r'^create/$', client_create, name='create'),
    url(r'^poll/$', client_poll, name='poll'),
    url(r'^detail/(?P<id>\d+)/$', client_detail, name='detail'),
    url(r'^detail/(?P<id>\d+)/delete/$', client_delete, name='delete'),
    url(r'^detail/(?P<id>\d+)/update/$', client_update, name='update'),
    url(r'^detail/(?P<id>\d+)/vote/$', vote_for_client, name='vote_for_client'),
    url(r'^poll/(?P<id>\d+)/vote/$', vote_for_client_poll, name='vote_for_client_poll'),
]

src/kmtest/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include("clients.urls", namespace='clients')),
    url(r'^', include("clients.urls", namespace='clients')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/clients/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.


def upload_location(instance, filename):
    return "db-img/{}".format(filename)


class Client(models.Model):
    first_name = models.CharField(max_length=120)
    second_name = models.CharField(max_length=120)
    age = models.IntegerField(default=0)
    birth_date = models.DateField()
    photo = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True)
    likes = models.IntegerField(default=0)  # FIXME: add constraint 0 <= likes <= 10

    def __unicode__(self):
        return u"{} {}".format(self.first_name, self.second_name)

    def __str__(self):
        return "{} {}".format(self.first_name, self.second_name)

    def get_absolute_url(self):
        return reverse("clients:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ["first_name", "second_name"]

src/clients/forms.py
import datetime
from django import forms

from .models import Client

CURRENT_YEAR = int(datetime.datetime.now().year)
BIRTH_YEAR_CHOICES = tuple(y for y in xrange(1900, CURRENT_YEAR, 1))


class ClientForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES))

    class Meta:
        model = Client
        fields = [
            "first_name",
            "second_name",
            "age",
            "birth_date",
            "photo"
        ]

src/clients/views.py
import os
import uuid

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404


from .models import Client
from .forms import ClientForm
import tasks as task

# Create your views here.


@login_required
def client_create(request):
    createForm = ClientForm(request.POST or None, request.FILES or None)

    if createForm.is_valid():
        instance = createForm.save(commit=False)
        instance.save()

        messages.success(request, "Succesfully created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "form": createForm,
    }

    return render(request, "clients/edit.html", context)


def client_list(request, _reportpath=''):
    # filter clients
    fltr_firstname = request.GET.get("qfirstname") or ''
    fltr_secondname = request.GET.get("qsecondname") or ''

    query_list = Client.objects.filter(
                        Q(first_name__icontains=fltr_firstname) &
                        Q(second_name__icontains=fltr_secondname)
                        )

    orderField = request.GET.get("o")

    if orderField:
        query_list = query_list.order_by(orderField)

    template = "clients/list.html"
    context = {
        "record_list": query_list,
        "title": "Clients List",
        "report_path": _reportpath,
    }

    return render(request, template, context)


def client_detail(request, id=None):
    instance = get_object_or_404(Client, id=id)

    context = {
        "title":  instance,
        "instance": instance,
    }

    return render(request, "clients/detail.html", context)


@login_required
def client_update(request, id=None):
    instance = get_object_or_404(Client, id=id)
    updateForm = ClientForm(request.POST or None, request.FILES or None, instance=instance)

    if updateForm.is_valid():
        instance = updateForm.save(commit=False)
        instance.save()
        messages.success(request, "Successfuly saved")

        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title":  instance,
        "instance": instance,
        "form": updateForm,
    }

    return render(request, "clients/edit.html", context)


@login_required
def client_delete(request, id=None):
    instance = get_object_or_404(Client, id=id)
    instance.delete()
    messages.success(request, "Successfuly deleted")

    return redirect("clients:list")


def download_report(request):
    filecode = str(uuid.uuid4())[:6].replace('-', '').lower()
    filename = "report_{}.xlsx".format(filecode)
    reportfile = os.path.join(settings.MEDIA_ROOT, "reports", filename)

    # print("DEBUG: {}\n".format(reportfile))

    task.generate_report.delay(reportfile)

    return client_list(request, settings.MEDIA_URL + "reports/{}".format(filename))


def vote_for_client(request, id=None):
    if not id:
        return Http404

    task.like_the_client.delay(id)

    return redirect('clients:detail', id=id)


def vote_for_client_poll(request, id=None):
    if not id:
        return Http404

    task.like_the_client.delay(id)

    return redirect('clients:poll')


def client_poll(request):
    query_list = Client.objects.all()

    template = "clients/poll.html"
    context = {
        "record_list": query_list,
        "title": "Clients Poll",
    }

    return render(request, template, context)

src/clients/templates/clients/detail.html
{% extends "base.html"%}

{% block head_title %} 
    {{ title }} | {{ block.super }} 
{% endblock head_title %}    

{% block content %}
    <div class="col-sm-3 text-center">
        {% if instance.photo %}
           <img src="{{ instance.photo.url }}" class="img-responsive">
        {% endif %}
        <hr/>
        {% if instance.likes >= 10 %}
            <a href="" class="btn btn-small btn-primary disabled" role="button">+1</a>
        {% else %}
            <a href="{% url 'clients:vote_for_client' id=instance.id %}" class="btn btn-small btn-primary" role="button">+1</a>    
        {% endif %}
        
        <b id="like_count">{{ instance.likes }}</b> likes

        <hr/>
        {% if user.is_authenticated %}
            <a href="{% url 'clients:update' id=instance.id %}" class="btn btn-success" role="button">Edit</a>    
        {% endif %}
        
    </div>
    <div class="col-sm-9">
        Name: {{ instance.first_name }} <br/>
        Second name: {{ instance.second_name }} <br/>
        Age: {{ instance.age }} <br/>
        Birth: {{ instance.birth_date | date:"d M Y"}} <br/>

    </div>
    <hr/>
    <div class="col-sm-12 text-center">
        <a href="{% url 'clients:poll' %}" class="btn btn-primary" role="button">Go to poll</a>
        <a href="{%url 'clients:list' %}" class="btn btn-warning">Back to the list</a>
    </div>
    
{% endblock content %}

src/clients/templates/clients/edit.html
{% extends "base.html"%}

{% block head_title %} 
    {% if  instance %}
        {{ instance }} | {{ block.super }}     
    {% else %}
        Add new client | {{ block.super }} 
    {% endif %}
    
{% endblock head_title %}

{% block content %}
    <div class="col-sm-3 text-center">
    {% if instance.photo %}
       <img src="{{ instance.photo.url }}" class="img-responsive">
    {% endif %}
    </div>

    <div class="col-sm-9">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            
            <button type="submit" class="btn btn-success" value="Add client"/>Save</button>

            <button type="reset" class="btn btn-primary" value="Reset">Reset</button>
            <a href="{%url 'clients:list' %}" class="btn btn-warning">Back to the list</a>
        </form>    
    </div>
    
{% endblock content %}

src/clients/templates/clients/list.html
{% extends "base.html"%}

{% block head_title %} 
    {{ title }} | {{ block.super }} 
{% endblock head_title %}

{% block content %}
    <div class="col-sm-12 text-left">

    {% if user.is_authenticated %}
        <a href="{% url 'clients:create' %}" class="btn btn-success" role="button">Add a new client</a>    
    {% endif %}

        <a href="{% url 'clients:poll' %}" class="btn btn-primary" role="button">Go to poll</a>    
    </div>
    <div class="col-sm-12 text-right">
        
        
        {% if report_path %}
            <a href="{{ report_path }}" >Download report.xlsx</a>
        {% else %}
            <a href="{% url 'clients:download_report' %}" class="btn btn-primary" role="button">Export to Excel</a>
        {% endif %}
        
    </div>
    <form method="GET" action="">
        <input type="text" name="qfirstname" placeholder="Filter by Name" value="{{ request.GET.qfirstname }}"></input>
        <input type="text" name="qsecondname" placeholder="Filter by Second Name" value="{{ request.GET.qsecondname }}"></input>
        <input type="submit" value="Filter" class="btn btn-primary"></input>
    </form>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th><a href="?qfirstname={{ request.GET.qfirstname }}&qsecondname={{ request.GET.qsecondname }}&o=first_name">First name</a></th>
                <th><a href="?qfirstname={{ request.GET.qfirstname }}&qsecondname={{ request.GET.qsecondname }}&o=second_name">Second name</a></th>
                <th><a href="?qfirstname={{ request.GET.qfirstname }}&qsecondname={{ request.GET.qsecondname }}&o=age">Age</a></th>
                <th><a href="?qfirstname={{ request.GET.qfirstname }}&qsecondname={{ request.GET.qsecondname }}&o=birth_date">Birthdate</a></th>
                <th></th>
            </tr>    
        </thead>
        <tbody>

    {% for rec in record_list %}
            <tr>
                <td><a href="{{ rec.get_absolute_url }}" class="btn btn-primary" role="button">View</a> &nbsp{{ rec.first_name }}</td>
                <td>{{ rec.second_name }}</td>
                <td>{{ rec.age }}</td>
                <td>{{ rec.birth_date | date:"d.m.Y"}}</td>
                <td>
                    {% if user.is_authenticated %}
                        <a href="{% url 'clients:delete' id=rec.id %}" class="btn btn-danger" role="button">Delete</a>
                        <a href="{% url 'clients:update' id=rec.id %}" class="btn btn-success" role="button">Edit</a>    
                    {% endif %}
                    
                </td>
            </tr> 
    {% empty %}   
        <tr><td colspan="4"><p>Sorry, no records found.</p></td></tr>
    {% endfor %}                
    
        </tbody>
    </table>
    
{% endblock content %}

src/clients/templates/clients/poll.html
{% extends "base.html"%}

{% block head_title %} 
    {{ title }} | {{ block.super }} 
{% endblock head_title %}

{% block content %}
    <div class="col-sm-12 text-center">
        <a href="{%url 'clients:list' %}" class="btn btn-warning">Back to the list</a>
    </div>

    {% for rec in record_list %}
    
        <div class="row">
            <div class="col-lg-2 col-sm-6">
                {% if rec.photo %}
                   <img src="{{ rec.photo.url }}" class="img-responsive img-thumbnail">
                {% endif %}
            </div>
            <div>
                <p> {{ rec }} </p>
            </div>
            <div>
                <a href="{{ rec.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
                {% if rec.likes >= 10 %}
                    <a href="" class="btn btn-small btn-primary disabled" role="button">+1</a>
                {% else %}
                    <a href="{% url 'clients:vote_for_client_poll' id=rec.id %}" class="btn btn-small btn-primary" role="button">+1</a>    
                {% endif %}
                
                <b id="like_count">{{ rec.likes }}</b> likes
            </div>
        </div>

    {% empty %}   

        <div><p> Sorry, no records found.</p></div>

    {% endfor %}                
    
    <div class="col-sm-12 text-center">
        <a href="{%url 'clients:list' %}" class="btn btn-warning">Back to the list</a>
    </div>
    
{% endblock content %}

src/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block head_title %} CRUD {% endblock head_title %}
    </title>

    <!-- Boostrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">    

    <!-- app css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>  
    
</head>
<body>
    
    <dir class="baseheader">
        Clients (header) | To log in - user:qwerty123456
    </dir>
    
    <div class="col-sm-8 col-sm-offset-2">
        {% include "messages_display.html" %}    
    </div>

    
    
    <div class="container">
        {% block content %} {% endblock content %}
        
        
    </div>
    
    <dir class="basefooter">
        CRUD python test application
    </dir>
        
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

src/templates/messages_display.html
 {% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                {% if "html_safe" in message.tags %}
                    {{ message|safe }}
                {% else %}
                   {{ message }}
                {% endif %}
            </div>
            {% endfor %}
        </ul>
    </div>
{% endif %}